export class BusquedaModel {
    GLOBAL: string = '';
    INDICADOR: number = 0;
    TYPE: string = '';
    FRESOLUTION: string = '';
    DELITO: string = '';
    RECURSO: string = '';
    OJURISDICCIONAL: string = '';
    RESUMEN: string = '';
    SHORTSUMMARY: string = '';
    MAGISTRATES: string = '';
    JVINCULANTE: string = '';
    MATERIA: string = '';
    JURISDICCION: string = '';
    TPONRMA: string = '';
    NMRCN: string = '';
    AMBIT: string = '';
    VDESIDENTE: string = '';
    CVOTE: string = '';
    INIT: number;
    ROWS: number;
    DESC: string = null;
    CESTDO: string;
    ID?: number = 0;
    IDENTRIE?: number = 0;
    UEDCN?: string = '';
    BLOG?: string = '';
    IDUSR?: number = 0;
    OEMISOR?: string = '';
    IDDIRECTORIO?: number = 0;
    KEYWORDS: string = '';
    TEMA: string = '';
    SUBTEMA: string = '';
    FRESOLUTIONSTRING: string = '';
}