export class AsistenciaModel {
    ID?: number = null;
    IDEVENTO?: number = null;
    TIPO?: number = null;
    EVENTO?: string = null;
    CODIGO?: string = null;
    NOMBRES?: string = null;
    APELLIDOS?: string = null;
    DNI?: string = null;
    CORREO?: string = null;
    REGISTRADO?: boolean = null;
    CDESTDO?: string = null;
    UCRCN?: string = null;
    FCRCN?: Date = null;
    ASISTENTES?: string = null;
    FEDCN?: Date = null;
    FINGRESO?: Date = null;
    FSALIDA?: Date = null;
    FINGRESO2?: string = null;
    FSALIDA2?: string = null;
    FECHA?: Date = null;
    TIEMPO?: string = null;
    FINGRESO1?: string = null;
    FSALIDA1?: string = null;
    REGISTROS?: string = null;
}